services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres
    networks:
      - backend
    volumes:
      - app_volume:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.app
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:

volumes:
  app_volume:
    driver: local
