#logging:
#  level:
#    ROOT: DEBUG

spring:
  application:
    name: depot
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      validation-timeout: 300000
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # create-drop #
  sql:
    init:
      platform: postgres

application:
  security:
    jwt:
      expiration: 86400000  # 1 day in milliseconds

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

custom:
  inventory:
    max-depot-space: 10000
    max-inventory-space: 1000
    auto-reorder: true
    low-stock-alert: true
    expiration-alert: true
