spring:
  application:
    name: depot
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000  # 1 day in milliseconds

custom:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}